CREATE TABLE ActiveAgent (
  `U_DateAssignedToOrg` DATE default '0000-00-00' not null COMMENT 'Date Assigned to Office',
  `U_LoginName` VARCHAR(20) COMMENT 'Agent Logon Name',
  `U_Password` VARCHAR(20) COMMENT 'Agent Password',
  `U_SecurityLevel` INT(3) COMMENT 'Security Level',
  `U_HiddenUsCID` VARCHAR(50) COMMENT 'Agent Type',
  `U_AgentTypeChangeDate` DATE default '0000-00-00' not null COMMENT 'Date Agent Type Changed',
  `U_FreeFormDesig` VARCHAR(15) COMMENT 'Agent Designation',
  `U_UserSalutation` VARCHAR(6) COMMENT 'Agent Salutation',
  `U_UserFirstName` VARCHAR(50) COMMENT 'Agent First Name',
  `U_UserLastName` VARCHAR(50) COMMENT 'Agent Last Name',
  `U_UserMI` VARCHAR(1) COMMENT 'Agent Middle Initial',
  `U_AddressStreet` VARCHAR(50) COMMENT 'Agent Address Street Name',
  `U_Address2` VARCHAR(50) COMMENT 'Agent Address2',
  `U_City` VARCHAR(50) COMMENT 'Agent City',
  `U_State` VARCHAR(50) COMMENT 'Agent State',
  `U_Zip` VARCHAR(20) COMMENT 'Agent Zip',
  `U_MailAddressStreet` VARCHAR(50) COMMENT 'Agent Mail Street Name',
  `U_MailAddress2` VARCHAR(50) COMMENT 'Agent Mail Address2',
  `U_MailCity` VARCHAR(50) COMMENT 'Agent Mail City',
  `U_MailState` VARCHAR(50) COMMENT 'Agent Mail State',
  `U_MailZip` VARCHAR(20) COMMENT 'Agent Mail Zip',
  `U_PhoneNumber1Desc` VARCHAR(5) COMMENT 'Agent Phone1 Description',
  `U_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'Agent Phone1 CountryId',
  `U_PhoneNumber1` VARCHAR(30) COMMENT 'Agent Phone1 Number',
  `U_PhoneNumber1Ext` VARCHAR(5) COMMENT 'Agent Phone1 Extension',
  `U_PhoneNumber2Desc` VARCHAR(5) COMMENT 'Agent Phone2 Description',
  `U_PhoneNumber2CountryCodeId` VARCHAR(50) COMMENT 'Agent Phone2 CountryId',
  `U_PhoneNumber2` VARCHAR(30) COMMENT 'Agent Phone2 Number',
  `U_PhoneNumber2Ext` VARCHAR(5) COMMENT 'Agent Phone2 Extension',
  `U_PhoneNumber3Desc` VARCHAR(5) COMMENT 'Agent Phone3 Description',
  `U_PhoneNumber3CountryCodeId` VARCHAR(50) COMMENT 'Agent Phone3 CountryId',
  `U_PhoneNumber3` VARCHAR(30) COMMENT 'Agent Phone3 Number',
  `U_PhoneNumber3Ext` VARCHAR(5) COMMENT 'Agent Phone3 Extension',
  `U_PhoneNumber4Desc` VARCHAR(5) COMMENT 'Agent Phone4 Description',
  `U_PhoneNumber4CountryCodeId` VARCHAR(50) COMMENT 'Agent Phone4 CountryId',
  `U_PhoneNumber4` VARCHAR(30) COMMENT 'Agent Phone4 Number',
  `U_PhoneNumber4Ext` VARCHAR(5) COMMENT 'Agent Phone4 Extension',
  `U_PhoneNumber5Desc` VARCHAR(5) COMMENT 'Agent Phone5 Description',
  `U_PhoneNumber5CountryCodeId` VARCHAR(50) COMMENT 'Agent Phone5 CountryId',
  `U_PhoneNumber5` VARCHAR(30) COMMENT 'Agent Phone5 Number',
  `U_PhoneNumber5Ext` VARCHAR(5) COMMENT 'Agent Phone5 Extension',
  `U_Email` VARCHAR(50) COMMENT 'Agent Email',
  `U_WebPage` VARCHAR(80) COMMENT 'Agent Url',
  `U_StateAgentIsMemberOf` VARCHAR(50) COMMENT 'State Agent Is Member Of',
  `U_StateAgentIsMemberOfDate` DATE default '0000-00-00' not null COMMENT 'Date of Agt State Mbrshp',
  `U_DuesPaidToBoard` VARCHAR(50) COMMENT 'Dues Paid to Board',
  `U_BoardDuesPaidThrough` VARCHAR(35) COMMENT 'Board Dues Paid Through',
  `U_PACLastContribCheckNum` VARCHAR(10) COMMENT 'Lst PAC Contrib Check #',
  `U_PreviousYearPACContrib` DECIMAL(8,2) COMMENT 'Prev Year PAC Contribute',
  `U_Dist` VARCHAR(50) COMMENT 'Distributed User',
  `U_LastTrig` DATE default '0000-00-00' not null COMMENT 'Last Trigger Date',
  `U_Photos` VARCHAR(50) COMMENT 'User Photos Code',
  `U_UpdateDate` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'Update Date',
  `U_UpdateAgent` INT(10) COMMENT 'Update By Agent',
  `U_InputDate` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'Date Added',
  `U_MultyLogin` VARCHAR(50) COMMENT 'Multiple Logon',
  `U_Hash` VARCHAR(32) COMMENT 'Hash',
  `U_Photographer` VARCHAR(1) COMMENT 'Photographer',
  `U_user_is_active` VARCHAR(50) COMMENT 'Active',
  `U_UserCode` VARCHAR(20) COMMENT 'User Code',
  `U_users_nrds_id` VARCHAR(9) COMMENT 'NRDS_ID',
  `AO_BranchOfOrgID` INT(10) COMMENT 'AOMain Office ID',
  `AO_HiddenOtyID` VARCHAR(50) COMMENT 'AOOffice Type',
  `AO_ShortName` VARCHAR(25) COMMENT 'AOOffice Abbreviation',
  `AO_OrganizationName` VARCHAR(100) COMMENT 'AOOffice Name',
  `AO_OrgAddressStreet` VARCHAR(50) COMMENT 'AOOffceAddressStreetName',
  `AO_OrgAddress2` VARCHAR(50) COMMENT 'AOOffice Address2',
  `AO_OrgCity` VARCHAR(50) COMMENT 'AOOffice City',
  `AO_OrgState` VARCHAR(50) COMMENT 'AOOffice State',
  `AO_OrgZip` VARCHAR(20) COMMENT 'AOOffice Zip',
  `AO_PhoneNumber1Desc` VARCHAR(10) COMMENT 'AOOfficePhone1Description',
  `AO_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'AOOffice Phone1 CountryId',
  `AO_PhoneNumber1` VARCHAR(30) COMMENT 'AOOffice Phone1 Number',
  `AO_PhoneNumber1Ext` VARCHAR(5) COMMENT 'AOOffice Phone1 Extension',
  `AO_EMail` VARCHAR(50) COMMENT 'AOOffice Email',
  `AO_WebPage` VARCHAR(80) COMMENT 'AOOffice Url',
  `AO_board_id` INT(10) COMMENT 'AOBoard ID',
  `UP_AgentPhone` INT(3) COMMENT 'UPPreferred Phone',
  `U_Status` VARCHAR(50) COMMENT 'Agent Status',
  `U_StatusDate` DATE default '0000-00-00' not null COMMENT 'Status Date',
  `U_Indoctrination` VARCHAR(50) COMMENT 'Agent Training',
  `U_IndoctrinationDate` DATE default '0000-00-00' not null COMMENT 'Training Date',
  `U_AgentLicenseID` VARCHAR(25) COMMENT 'Agent License ID',
  `U_AgentLicenseDate` DATE default '0000-00-00' not null COMMENT 'Agent License Date',
  `U_SpouseFirstName` VARCHAR(15) COMMENT 'Spouse First Name',
  `U_PreferredMailCode` VARCHAR(50) COMMENT 'Agent Mail Preference',
  `U_BirthDate` DATE default '0000-00-00' not null COMMENT 'Agent Birth Date',
  `U_LockBoxKeyNumber` VARCHAR(9) COMMENT 'Lock Box Number',
  `U_DateKeyAssigned` DATE default '0000-00-00' not null COMMENT 'Date Key Assigned',
  `U_PreviousKeyNumber` VARCHAR(9) COMMENT 'Previous Key Number',
  `U_NumberOfKeysAssigned` INT(5) COMMENT 'Number of Keys',
  `U_LockBoxKeyDeposit` DECIMAL(8,2) COMMENT 'Lock Box Key Deposit',
  `U_ActiveBookCount` INT(5) COMMENT 'Active Book Count',
  `U_SoldBookCount` INT(5) COMMENT 'Sold Book Count',
  `U_CorpPACContribYTD` DECIMAL(8,2) COMMENT 'Corp PAC Contribution YTD',
  `U_PersonalPACContrib` DECIMAL(8,2) COMMENT 'Pers PAC Contribution YTD',
  `U_PACLastContribDate` DATE default '0000-00-00' not null COMMENT 'Lst PAC Contribution Date',
  `U_AgentID` INT(10) COMMENT 'Agent Identifier',
  `U_HiddenOrgID` INT(10) COMMENT 'Agent Office ID',
  PRIMARY KEY(`U_AgentID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

