CREATE TABLE Property_CI_3 (
  `L_Type_` VARCHAR(50) COMMENT 'Type',
  `L_Area` VARCHAR(50) COMMENT 'Area',
  `L_SystemPrice` INT(10) COMMENT 'Search Price',
  `L_AskingPrice` INT(10) COMMENT 'Asking Price',
  `L_AddressNumber` VARCHAR(15) COMMENT 'Address Number',
  `L_AddressSearchNumber` INT(10) COMMENT 'Address Search Number',
  `L_AddressDirection` VARCHAR(2) COMMENT 'Address Direction',
  `L_AddressStreet` VARCHAR(50) COMMENT 'Address Street',
  `L_Address2` VARCHAR(50) COMMENT 'Address 2',
  `L_City` VARCHAR(50) COMMENT 'City',
  `L_State` VARCHAR(50) COMMENT 'State',
  `L_Zip` VARCHAR(20) COMMENT 'Zip',
  `L_StatusCatID` VARCHAR(50) COMMENT 'Status Category',
  `L_StatusID` VARCHAR(1) COMMENT 'Status Detail',
  `L_SaleRent` VARCHAR(50) COMMENT 'Sale/Rent',
  `L_Keyword1` VARCHAR(50) COMMENT 'Current Use',
  `L_Keyword2` VARCHAR(50) COMMENT 'Parking',
  `L_Keyword3` VARCHAR(50) COMMENT 'Sprinkler System',
  `L_Keyword7` VARCHAR(50) COMMENT 'Terms',
  `L_SquareFeet` INT(10) COMMENT 'Approx SqFt',
  `L_NumAcres` DECIMAL(18,2) COMMENT 'Number of Acres',
  `L_NumUnits` INT(5) COMMENT 'Number of Units',
  `L_ListAgent1` INT(10) COMMENT 'Agent',
  `L_ListOffice1` INT(10) COMMENT 'Listing Office 1',
  `L_ListAgent2` INT(10) COMMENT 'Listing Agent 2',
  `L_ListOffice2` INT(10) COMMENT 'Listing Office 2',
  `L_ListingDate` DATE default '0000-00-00' not null COMMENT 'Listing Date',
  `L_ExpirationDate` DATE default '0000-00-00' not null COMMENT 'Expiration Date',
  `L_OriginalPrice` INT(10) COMMENT 'Original Price',
  `L_Remarks` TEXT COMMENT 'Public Remarks',
  `L_HowSold` VARCHAR(50) COMMENT 'How Sold',
  `L_ContractDate` DATE default '0000-00-00' not null COMMENT 'Contract Date',
  `L_ClosingDate` DATE default '0000-00-00' not null COMMENT 'Closing Date',
  `L_SoldPrice` INT(10) COMMENT 'Sold Price',
  `L_SellingAgent1` INT(10) COMMENT 'Selling Agent 1',
  `L_SellingOffice1` INT(10) COMMENT 'Selling Office 1',
  `L_SellingAgent2` INT(10) COMMENT 'Selling Agent 2',
  `L_SellingOffice2` INT(10) COMMENT 'Selling Office 2',
  `L_HotSheetDate` DATE default '0000-00-00' not null COMMENT 'HotSheet Date',
  `L_StatusDate` DATE default '0000-00-00' not null COMMENT 'Status Date',
  `L_PriceDate` DATE default '0000-00-00' not null COMMENT 'Price Date',
  `L_InputDate` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'Input Date',
  `L_UpdateDate` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'Update Date',
  `L_PictureCount` INT(10) COMMENT 'Photo Count',
  `L_Last_Photo_updt` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'PhotoTimestamp',
  `L_OffMarketDate` DATE default '0000-00-00' not null COMMENT 'Off Market Date',
  `L_listings_associated_doc_count` INT(10) COMMENT 'Associated Document Count',
  `L_DisplayId` VARCHAR(4) COMMENT 'MLS #',
  `L_StreetDesignationId` VARCHAR(50) COMMENT 'Street Designation',
  `LMD_MP_Latitude` DECIMAL(18,15) COMMENT 'Geo Latitude',
  `LMD_MP_Longitude` DECIMAL(19,15) COMMENT 'Geo Longitude',
  `LMD_MP_Quality` DECIMAL(12,8) COMMENT 'Geo Quality',
  `LMD_MP_ZoomLevel` DECIMAL(2,0) COMMENT 'Geo Zoom Level',
  `LMD_MP_AddressLine` VARCHAR(255) COMMENT 'Geo Address Line',
  `LMD_MP_PrimaryCity` VARCHAR(100) COMMENT 'Geo Primary City',
  `LMD_MP_SecondaryCity` VARCHAR(100) COMMENT 'Geo Secondary City',
  `LMD_MP_Subdivision` VARCHAR(2) COMMENT 'Geo Subdivision',
  `LMD_MP_PostalCode` VARCHAR(10) COMMENT 'Geo Postal Code',
  `LMD_MP_MatchCode` INT(3) COMMENT 'Geo Match Code',
  `LMD_MP_MatchedMethod` INT(3) COMMENT 'Geo Matched Method',
  `LMD_MP_UpdateDate` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'Geo Update Timestamp',
  `L_FirstPhotoAddDt` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'First Photo Add Timestamp',
  `LM_Char25_21` VARCHAR(25) COMMENT 'Business Name',
  `LM_Char25_22` VARCHAR(25) COMMENT 'Business Phone',
  `LM_Char25_23` VARCHAR(50) COMMENT 'County',
  `LM_Char25_24` VARCHAR(25) COMMENT 'Furn Fix and Equip $',
  `LM_Int4_1` INT(10) COMMENT 'Year Built',
  `LM_Dec_2` DECIMAL(18,2) COMMENT 'Sold Price per SQFT',
  `LM_char5_1` VARCHAR(50) COMMENT 'Seller Concessions Y/N',
  `LM_char5_2` VARCHAR(50) COMMENT 'REO Y/N',
  `LM_char5_3` VARCHAR(50) COMMENT 'Short Sale',
  `LM_char100_1` VARCHAR(100) COMMENT 'Seller Concessions',
  `LM_char255_1` VARCHAR(255) COMMENT 'Directions',
  `VT_VTourURL` VARCHAR(255) COMMENT 'Virtual Tour',
  `LVC_Agent_Hit_Count` INT(10) COMMENT 'Agent Hit Count',
  `LVC_Client_Hit_Count` INT(10) COMMENT 'Client Hit Count',
  `T_tax_db_id` INT(3) COMMENT 'Tax Database ID',
  `T_list_tax_property_id` VARCHAR(50) COMMENT 'Tax Property ID',
  `LFD_AVAILABLEFINANCING_30` TEXT COMMENT 'AVAILABLE FINANCING',
  `LFD_INTERIORCONDITION_31` TEXT COMMENT 'INTERIOR CONDITION',
  `LFD_EXTERIORCONDITION_32` TEXT COMMENT 'EXTERIOR CONDITION',
  `LFD_BUSINESSDESCRIPTION_33` TEXT COMMENT 'BUSINESS DESCRIPTION',
  `LFD_ROOF_34` TEXT COMMENT 'ROOF',
  `LFD_BUILDINGEXTERIOR_35` TEXT COMMENT 'BUILDING EXTERIOR',
  `LFD_PROPERTYDESCRIPTION_36` TEXT COMMENT 'PROPERTY DESCRIPTION',
  `LFD_WATERSEWER_37` TEXT COMMENT 'WATER/SEWER',
  `LFD_INTERIORFEATURES_38` TEXT COMMENT 'INTERIOR FEATURES',
  `LFD_UTILITIES_39` TEXT COMMENT 'UTILITIES',
  `LFD_HEATINGSYSTEM_40` TEXT COMMENT 'HEATING SYSTEM',
  `LFD_STREETROADINFORMATION_41` TEXT COMMENT 'STREET/ROAD INFORMATION',
  `LFD_EXTERIORFEATURES_42` TEXT COMMENT 'EXTERIOR FEATURES',
  `LFD_AGENTINFORMATION_43` TEXT COMMENT 'AGENT INFORMATION',
  `LFD_CLOSINGPOSSESSION_44` TEXT COMMENT 'CLOSING/POSSESSION',
  `LFD_INTERNET_45` TEXT COMMENT 'INTERNET',
  `LR_remarks11` TEXT COMMENT 'Agent Only Remarks',
  `LA1_LoginName` VARCHAR(20) COMMENT 'LA1Agent Logon Name',
  `LA1_HiddenUsCID` VARCHAR(50) COMMENT 'LA1Agent Type',
  `LA1_UserFirstName` VARCHAR(50) COMMENT 'LA1Agent First Name',
  `LA1_UserLastName` VARCHAR(50) COMMENT 'LA1Agent Last Name',
  `LA1_UserMI` VARCHAR(1) COMMENT 'LA1Agent Middle Initial',
  `LA1_AddressStreet` VARCHAR(50) COMMENT 'LA1AgentAddressStreetName',
  `LA1_Address2` VARCHAR(50) COMMENT 'LA1Agent Address2',
  `LA1_City` VARCHAR(50) COMMENT 'LA1Agent City',
  `LA1_State` VARCHAR(50) COMMENT 'LA1Agent State',
  `LA1_Zip` VARCHAR(20) COMMENT 'LA1Agent Zip',
  `LA1_PhoneNumber1Desc` VARCHAR(5) COMMENT 'LA1AgentPhone1Description',
  `LA1_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'LA1Agent Phone1 CountryId',
  `LA1_PhoneNumber1` VARCHAR(30) COMMENT 'LA1Agent Phone1 Number',
  `LA1_PhoneNumber1Ext` VARCHAR(5) COMMENT 'LA1Agent Phone1 Extension',
  `LA1_PhoneNumber2Desc` VARCHAR(5) COMMENT 'LA1AgentPhone2Description',
  `LA1_PhoneNumber2CountryCodeId` VARCHAR(50) COMMENT 'LA1Agent Phone2 CountryId',
  `LA1_PhoneNumber2` VARCHAR(30) COMMENT 'LA1Agent Phone2 Number',
  `LA1_PhoneNumber2Ext` VARCHAR(5) COMMENT 'LA1Agent Phone2 Extension',
  `LA1_PhoneNumber3Desc` VARCHAR(5) COMMENT 'LA1AgentPhone3Description',
  `LA1_PhoneNumber3CountryCodeId` VARCHAR(50) COMMENT 'LA1Agent Phone3 CountryId',
  `LA1_PhoneNumber3` VARCHAR(30) COMMENT 'LA1Agent Phone3 Number',
  `LA1_PhoneNumber3Ext` VARCHAR(5) COMMENT 'LA1Agent Phone3 Extension',
  `LA1_PhoneNumber4Desc` VARCHAR(5) COMMENT 'LA1AgentPhone4Description',
  `LA1_PhoneNumber4CountryCodeId` VARCHAR(50) COMMENT 'LA1Agent Phone4 CountryId',
  `LA1_PhoneNumber4` VARCHAR(30) COMMENT 'LA1Agent Phone4 Number',
  `LA1_PhoneNumber4Ext` VARCHAR(5) COMMENT 'LA1Agent Phone4 Extension',
  `LA1_PhoneNumber5Desc` VARCHAR(5) COMMENT 'LA1AgentPhone5Description',
  `LA1_PhoneNumber5CountryCodeId` VARCHAR(50) COMMENT 'LA1Agent Phone5 CountryId',
  `LA1_PhoneNumber5` VARCHAR(30) COMMENT 'LA1Agent Phone5 Number',
  `LA1_PhoneNumber5Ext` VARCHAR(5) COMMENT 'LA1Agent Phone5 Extension',
  `LA1_Email` VARCHAR(50) COMMENT 'LA1Agent Email',
  `LA1_WebPage` VARCHAR(80) COMMENT 'LA1Agent Url',
  `LA1_Status` VARCHAR(50) COMMENT 'LA1Agent Status',
  `LA2_UserFirstName` VARCHAR(50) COMMENT 'LA2Agent First Name',
  `LA2_UserLastName` VARCHAR(50) COMMENT 'LA2Agent Last Name',
  `LA2_UserMI` VARCHAR(1) COMMENT 'LA2Agent Middle Initial',
  `LA2_AddressStreet` VARCHAR(50) COMMENT 'LA2AgentAddressStreetName',
  `LA2_Address2` VARCHAR(50) COMMENT 'LA2Agent Address2',
  `LA2_City` VARCHAR(50) COMMENT 'LA2Agent City',
  `LA2_State` VARCHAR(50) COMMENT 'LA2Agent State',
  `LA2_Zip` VARCHAR(20) COMMENT 'LA2Agent Zip',
  `LA2_PhoneNumber1Desc` VARCHAR(5) COMMENT 'LA2AgentPhone1Description',
  `LA2_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'LA2Agent Phone1 CountryId',
  `LA2_PhoneNumber1` VARCHAR(30) COMMENT 'LA2Agent Phone1 Number',
  `LA2_PhoneNumber1Ext` VARCHAR(5) COMMENT 'LA2Agent Phone1 Extension',
  `LA2_PhoneNumber2Desc` VARCHAR(5) COMMENT 'LA2AgentPhone2Description',
  `LA2_PhoneNumber2CountryCodeId` VARCHAR(50) COMMENT 'LA2Agent Phone2 CountryId',
  `LA2_PhoneNumber2` VARCHAR(30) COMMENT 'LA2Agent Phone2 Number',
  `LA2_PhoneNumber2Ext` VARCHAR(5) COMMENT 'LA2Agent Phone2 Extension',
  `LA2_PhoneNumber3Desc` VARCHAR(5) COMMENT 'LA2AgentPhone3Description',
  `LA2_PhoneNumber3CountryCodeId` VARCHAR(50) COMMENT 'LA2Agent Phone3 CountryId',
  `LA2_PhoneNumber3` VARCHAR(30) COMMENT 'LA2Agent Phone3 Number',
  `LA2_PhoneNumber3Ext` VARCHAR(5) COMMENT 'LA2Agent Phone3 Extension',
  `LA2_PhoneNumber4Desc` VARCHAR(5) COMMENT 'LA2AgentPhone4Description',
  `LA2_PhoneNumber4CountryCodeId` VARCHAR(50) COMMENT 'LA2Agent Phone4 CountryId',
  `LA2_PhoneNumber4` VARCHAR(30) COMMENT 'LA2Agent Phone4 Number',
  `LA2_PhoneNumber4Ext` VARCHAR(5) COMMENT 'LA2Agent Phone4 Extension',
  `LA2_PhoneNumber5Desc` VARCHAR(5) COMMENT 'LA2AgentPhone5Description',
  `LA2_PhoneNumber5CountryCodeId` VARCHAR(50) COMMENT 'LA2Agent Phone5 CountryId',
  `LA2_PhoneNumber5` VARCHAR(30) COMMENT 'LA2Agent Phone5 Number',
  `LA2_PhoneNumber5Ext` VARCHAR(5) COMMENT 'LA2Agent Phone5 Extension',
  `LA2_Email` VARCHAR(50) COMMENT 'LA2Agent Email',
  `LA2_WebPage` VARCHAR(80) COMMENT 'LA2Agent Url',
  `LA2_Status` VARCHAR(50) COMMENT 'LA2Agent Status',
  `SA1_HiddenUsCID` VARCHAR(50) COMMENT 'SA1Agent Type',
  `SA1_UserFirstName` VARCHAR(50) COMMENT 'SA1Agent First Name',
  `SA1_UserLastName` VARCHAR(50) COMMENT 'SA1Agent Last Name',
  `SA1_UserMI` VARCHAR(1) COMMENT 'SA1Agent Middle Initial',
  `SA1_AddressStreet` VARCHAR(50) COMMENT 'SA1AgentAddressStreetName',
  `SA1_Address2` VARCHAR(50) COMMENT 'SA1Agent Address2',
  `SA1_City` VARCHAR(50) COMMENT 'SA1Agent City',
  `SA1_State` VARCHAR(50) COMMENT 'SA1Agent State',
  `SA1_Zip` VARCHAR(20) COMMENT 'SA1Agent Zip',
  `SA1_PhoneNumber1Desc` VARCHAR(5) COMMENT 'SA1AgentPhone1Description',
  `SA1_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'SA1Agent Phone1 CountryId',
  `SA1_PhoneNumber1` VARCHAR(30) COMMENT 'SA1Agent Phone1 Number',
  `SA1_PhoneNumber1Ext` VARCHAR(5) COMMENT 'SA1Agent Phone1 Extension',
  `SA1_PhoneNumber2Desc` VARCHAR(5) COMMENT 'SA1AgentPhone2Description',
  `SA1_PhoneNumber2CountryCodeId` VARCHAR(50) COMMENT 'SA1Agent Phone2 CountryId',
  `SA1_PhoneNumber2` VARCHAR(30) COMMENT 'SA1Agent Phone2 Number',
  `SA1_PhoneNumber2Ext` VARCHAR(5) COMMENT 'SA1Agent Phone2 Extension',
  `SA1_PhoneNumber3Desc` VARCHAR(5) COMMENT 'SA1AgentPhone3Description',
  `SA1_PhoneNumber3CountryCodeId` VARCHAR(50) COMMENT 'SA1Agent Phone3 CountryId',
  `SA1_PhoneNumber3` VARCHAR(30) COMMENT 'SA1Agent Phone3 Number',
  `SA1_PhoneNumber3Ext` VARCHAR(5) COMMENT 'SA1Agent Phone3 Extension',
  `SA1_PhoneNumber4Desc` VARCHAR(5) COMMENT 'SA1AgentPhone4Description',
  `SA1_PhoneNumber4CountryCodeId` VARCHAR(50) COMMENT 'SA1Agent Phone4 CountryId',
  `SA1_PhoneNumber4` VARCHAR(30) COMMENT 'SA1Agent Phone4 Number',
  `SA1_PhoneNumber4Ext` VARCHAR(5) COMMENT 'SA1Agent Phone4 Extension',
  `SA1_PhoneNumber5Desc` VARCHAR(5) COMMENT 'SA1AgentPhone5Description',
  `SA1_PhoneNumber5CountryCodeId` VARCHAR(50) COMMENT 'SA1Agent Phone5 CountryId',
  `SA1_PhoneNumber5` VARCHAR(30) COMMENT 'SA1Agent Phone5 Number',
  `SA1_PhoneNumber5Ext` VARCHAR(5) COMMENT 'SA1Agent Phone5 Extension',
  `SA1_Email` VARCHAR(50) COMMENT 'SA1Agent Email',
  `SA1_WebPage` VARCHAR(80) COMMENT 'SA1Agent Url',
  `SA1_Status` VARCHAR(50) COMMENT 'SA1Agent Status',
  `SA2_UserFirstName` VARCHAR(50) COMMENT 'SA2Agent First Name',
  `SA2_UserLastName` VARCHAR(50) COMMENT 'SA2Agent Last Name',
  `SA2_UserMI` VARCHAR(1) COMMENT 'SA2Agent Middle Initial',
  `SA2_AddressStreet` VARCHAR(50) COMMENT 'SA2AgentAddressStreetName',
  `SA2_Address2` VARCHAR(50) COMMENT 'SA2Agent Address2',
  `SA2_City` VARCHAR(50) COMMENT 'SA2Agent City',
  `SA2_State` VARCHAR(50) COMMENT 'SA2Agent State',
  `SA2_Zip` VARCHAR(20) COMMENT 'SA2Agent Zip',
  `SA2_PhoneNumber1Desc` VARCHAR(5) COMMENT 'SA2AgentPhone1Description',
  `SA2_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'SA2Agent Phone1 CountryId',
  `SA2_PhoneNumber1` VARCHAR(30) COMMENT 'SA2Agent Phone1 Number',
  `SA2_PhoneNumber1Ext` VARCHAR(5) COMMENT 'SA2Agent Phone1 Extension',
  `SA2_PhoneNumber2Desc` VARCHAR(5) COMMENT 'SA2AgentPhone2Description',
  `SA2_PhoneNumber2CountryCodeId` VARCHAR(50) COMMENT 'SA2Agent Phone2 CountryId',
  `SA2_PhoneNumber2` VARCHAR(30) COMMENT 'SA2Agent Phone2 Number',
  `SA2_PhoneNumber2Ext` VARCHAR(5) COMMENT 'SA2Agent Phone2 Extension',
  `SA2_PhoneNumber3Desc` VARCHAR(5) COMMENT 'SA2AgentPhone3Description',
  `SA2_PhoneNumber3CountryCodeId` VARCHAR(50) COMMENT 'SA2Agent Phone3 CountryId',
  `SA2_PhoneNumber3` VARCHAR(30) COMMENT 'SA2Agent Phone3 Number',
  `SA2_PhoneNumber3Ext` VARCHAR(5) COMMENT 'SA2Agent Phone3 Extension',
  `SA2_PhoneNumber4Desc` VARCHAR(5) COMMENT 'SA2AgentPhone4Description',
  `SA2_PhoneNumber4CountryCodeId` VARCHAR(50) COMMENT 'SA2Agent Phone4 CountryId',
  `SA2_PhoneNumber4` VARCHAR(30) COMMENT 'SA2Agent Phone4 Number',
  `SA2_PhoneNumber4Ext` VARCHAR(5) COMMENT 'SA2Agent Phone4 Extension',
  `SA2_PhoneNumber5Desc` VARCHAR(5) COMMENT 'SA2AgentPhone5Description',
  `SA2_PhoneNumber5CountryCodeId` VARCHAR(50) COMMENT 'SA2Agent Phone5 CountryId',
  `SA2_PhoneNumber5` VARCHAR(30) COMMENT 'SA2Agent Phone5 Number',
  `SA2_PhoneNumber5Ext` VARCHAR(5) COMMENT 'SA2Agent Phone5 Extension',
  `SA2_Email` VARCHAR(50) COMMENT 'SA2Agent Email',
  `SA2_WebPage` VARCHAR(80) COMMENT 'SA2Agent Url',
  `SA2_Status` VARCHAR(50) COMMENT 'SA2Agent Status',
  `LO1_HiddenOrgID` INT(10) COMMENT 'LO1Office Identifier',
  `LO1_BranchOfOrgID` INT(10) COMMENT 'LO1Main Office ID',
  `LO1_HiddenOtyID` VARCHAR(50) COMMENT 'LO1Office Type',
  `LO1_ShortName` VARCHAR(25) COMMENT 'LO1Office Abbreviation',
  `LO1_OrganizationName` VARCHAR(100) COMMENT 'LO1Office Name',
  `LO1_OrgAddressStreet` VARCHAR(50) COMMENT 'LO1OffceAddressStreetName',
  `LO1_OrgAddress2` VARCHAR(50) COMMENT 'LO1Office Address2',
  `LO1_OrgCity` VARCHAR(50) COMMENT 'LO1Office City',
  `LO1_OrgState` VARCHAR(50) COMMENT 'LO1Office State',
  `LO1_OrgZip` VARCHAR(20) COMMENT 'LO1Office Zip',
  `LO1_PhoneNumber1Desc` VARCHAR(10) COMMENT 'LO1OfficePhone1Descriptin',
  `LO1_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'LO1OfficePhone1CountryId',
  `LO1_PhoneNumber1` VARCHAR(30) COMMENT 'LO1Office Phone1 Number',
  `LO1_PhoneNumber1Ext` VARCHAR(5) COMMENT 'LO1OfficePhone1Extension',
  `LO1_EMail` VARCHAR(50) COMMENT 'LO1Office Email',
  `LO1_WebPage` VARCHAR(80) COMMENT 'LO1Office Url',
  `LO1_board_id` INT(10) COMMENT 'LO1Board ID',
  `LO2_HiddenOrgID` INT(10) COMMENT 'LO2Office Identifier',
  `LO2_BranchOfOrgID` INT(10) COMMENT 'LO2Main Office ID',
  `LO2_HiddenOtyID` VARCHAR(50) COMMENT 'LO2Office Type',
  `LO2_ShortName` VARCHAR(25) COMMENT 'LO2Office Abbreviation',
  `LO2_OrganizationName` VARCHAR(100) COMMENT 'LO2Office Name',
  `LO2_OrgAddressStreet` VARCHAR(50) COMMENT 'LO2OffceAddressStreetName',
  `LO2_OrgAddress2` VARCHAR(50) COMMENT 'LO2Office Address2',
  `LO2_OrgCity` VARCHAR(50) COMMENT 'LO2Office City',
  `LO2_OrgState` VARCHAR(50) COMMENT 'LO2Office State',
  `LO2_OrgZip` VARCHAR(20) COMMENT 'LO2Office Zip',
  `LO2_PhoneNumber1Desc` VARCHAR(10) COMMENT 'LO2OfficePhone1Descriptin',
  `LO2_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'LO2OfficePhone1CountryId',
  `LO2_PhoneNumber1` VARCHAR(30) COMMENT 'LO2Office Phone1 Number',
  `LO2_PhoneNumber1Ext` VARCHAR(5) COMMENT 'LO2OfficePhone1Extension',
  `LO2_EMail` VARCHAR(50) COMMENT 'LO2Office Email',
  `LO2_WebPage` VARCHAR(80) COMMENT 'LO2Office Url',
  `LO2_board_id` INT(10) COMMENT 'LO2Board ID',
  `SO1_HiddenOrgID` INT(10) COMMENT 'SO1Office Identifier',
  `SO1_BranchOfOrgID` INT(10) COMMENT 'SO1Main Office ID',
  `SO1_HiddenOtyID` VARCHAR(50) COMMENT 'SO1Office Type',
  `SO1_ShortName` VARCHAR(25) COMMENT 'SO1Office Abbreviation',
  `SO1_OrganizationName` VARCHAR(100) COMMENT 'SO1Office Name',
  `SO1_OrgAddressStreet` VARCHAR(50) COMMENT 'SO1OffceAddressStreetName',
  `SO1_OrgAddress2` VARCHAR(50) COMMENT 'SO1Office Address2',
  `SO1_OrgCity` VARCHAR(50) COMMENT 'SO1Office City',
  `SO1_OrgState` VARCHAR(50) COMMENT 'SO1Office State',
  `SO1_OrgZip` VARCHAR(20) COMMENT 'SO1Office Zip',
  `SO1_PhoneNumber1Desc` VARCHAR(10) COMMENT 'SO1OfficePhone1Descriptin',
  `SO1_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'SO1OfficePhone1CountryId',
  `SO1_PhoneNumber1` VARCHAR(30) COMMENT 'SO1Office Phone1 Number',
  `SO1_PhoneNumber1Ext` VARCHAR(5) COMMENT 'SO1OfficePhone1Extension',
  `SO1_EMail` VARCHAR(50) COMMENT 'SO1Office Email',
  `SO1_WebPage` VARCHAR(80) COMMENT 'SO1Office Url',
  `SO1_board_id` INT(10) COMMENT 'SO1Board ID',
  `SO2_HiddenOrgID` INT(10) COMMENT 'SO2Office Identifier',
  `SO2_BranchOfOrgID` INT(10) COMMENT 'SO2Main Office ID',
  `SO2_HiddenOtyID` VARCHAR(50) COMMENT 'SO2Office Type',
  `SO2_ShortName` VARCHAR(25) COMMENT 'SO2Office Abbreviation',
  `SO2_OrganizationName` VARCHAR(100) COMMENT 'SO2Office Name',
  `SO2_OrgAddressStreet` VARCHAR(50) COMMENT 'SO2OffceAddressStreetName',
  `SO2_OrgAddress2` VARCHAR(50) COMMENT 'SO2Office Address2',
  `SO2_OrgCity` VARCHAR(50) COMMENT 'SO2Office City',
  `SO2_OrgState` VARCHAR(50) COMMENT 'SO2Office State',
  `SO2_OrgZip` VARCHAR(20) COMMENT 'SO2Office Zip',
  `SO2_PhoneNumber1Desc` VARCHAR(10) COMMENT 'SO2OfficePhone1Descriptin',
  `SO2_PhoneNumber1CountryCodeId` VARCHAR(50) COMMENT 'SO2OfficePhone1CountryId',
  `SO2_PhoneNumber1` VARCHAR(30) COMMENT 'SO2Office Phone1 Number',
  `SO2_PhoneNumber1Ext` VARCHAR(5) COMMENT 'SO2OfficePhone1Extension',
  `SO2_EMail` VARCHAR(50) COMMENT 'SO2Office Email',
  `SO2_WebPage` VARCHAR(80) COMMENT 'SO2Office Url',
  `SO2_board_id` INT(10) COMMENT 'SO2Board ID',
  `LV_vow_include` VARCHAR(50) COMMENT 'VOW Include',
  `LV_vow_address` VARCHAR(50) COMMENT 'VOW Address',
  `LV_vow_comment` VARCHAR(50) COMMENT 'VOW Comment',
  `LV_vow_avm` VARCHAR(50) COMMENT 'VOW AVM',
  `L_IdxInclude` VARCHAR(50) COMMENT 'IDX Include',
  `L_LastDocUpdate` DATETIME default '0000-00-00 00:00:00' not null COMMENT 'Doc Timestamp',
  `L_Address` VARCHAR(100) COMMENT 'Address',
  `L_Status` VARCHAR(50) COMMENT 'Status',
  `L_DOM` INT(10) COMMENT 'DOM',
  `L_DOMLS` INT(10) COMMENT 'DOMLS',
  `L_CDOM` INT(10) COMMENT 'Cumulative DOM',
  `LM_Char1_2` VARCHAR(50) COMMENT 'Variable',
  `LM_Char10_1` VARCHAR(10) COMMENT 'Coop',
  `LM_Char10_2` VARCHAR(50) COMMENT 'Bonus Y/N',
  `LM_Char10_3` VARCHAR(10) COMMENT 'Bonus Amount $',
  `LM_Char10_4` VARCHAR(50) COMMENT 'Paved Streets Y/N',
  `LM_Char10_5` VARCHAR(50) COMMENT 'Subdivision',
  `LM_Char10_7` VARCHAR(50) COMMENT 'Foundation',
  `LM_Char10_8` VARCHAR(50) COMMENT 'Water/Sewer',
  `LM_Char10_14` VARCHAR(10) COMMENT '% Leased',
  `LM_Char10_15` VARCHAR(10) COMMENT '# of Tenants',
  `LM_Char10_16` VARCHAR(10) COMMENT 'Lease Rate Per SQFT Annu',
  `LM_Char10_17` VARCHAR(50) COMMENT 'FIPS Code',
  `LM_Char25_1` VARCHAR(25) COMMENT 'Owner Name',
  `LM_Char25_2` VARCHAR(25) COMMENT 'Owner Phone',
  `LM_Char25_5` VARCHAR(25) COMMENT 'Zoning',
  `LM_Char25_6` VARCHAR(25) COMMENT 'Approx Lot Dimensions',
  `LM_Char25_7` VARCHAR(25) COMMENT 'APN #',
  `L_ListingID` INT(10) COMMENT 'SystemID',
  `L_Class` VARCHAR(50) COMMENT 'Class',
  `LA1_AgentID` VARCHAR(20) COMMENT 'LA1User Code',
  `LA2_HiddenUsCID` VARCHAR(50) COMMENT 'LA2Agent Type',
  `SA2_HiddenUsCID` VARCHAR(50) COMMENT 'SA2Agent Type',
  PRIMARY KEY(`L_ListingID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

